- set_fact:
    backup_dir: "/tmp/backup/{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"

- name: kill process
  shell: kill $(pgrep -f java)

- name: Ensure dir exists
  file:
    path: "{{backup_dir}}"
    state: directory


- name: back Xcode
  shell: mv /home/centos/hello/* "{{backup_dir}}"

- name: copy zip file
  unarchive:
    src: code.zip
    dest: /home/centos/hello

- name: start process
  shell: sh target/bin/webapp &
  async: 10000000
  poll: 0
